name: Stresty FHIR

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    services:
      pg:
        image: healthsamurai/aidboxdb:13.2
        env:
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: devbox
      devbox:
        image: healthsamurai/devbox:stable
        env:
          PGHOST: pg
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: devbox
          AIDBOX_CLIENT_ID: root
          AIDBOX_CLIENT_SECRET: secret
          AIDBOX_ADMIN_ID: admin
          AIDBOX_ADMIN_PASSWORD: secret
          AIDBOX_FHIR_VERSION: 4.0.0
          AIDBOX_LICENSE_ID:  ${{ secrets.LID }}
          AIDBOX_LICENSE_KEY: ${{ secrets.LKEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test bash
        run:  echo 'hello'

      - name: Test stresty
        run:  ./sty

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
