name: Stresty FHIR

on: [push]

jobs:
  stresty:
    runs-on: ubuntu-latest

    steps:

      - name: Get stresty
        run: curl -L https://github.com/HealthSamurai/stresty/releases/download/0.0.1-RC1/sty-ubuntu-latest.zip --output sty.zip

      - name: Unzip stresty
        run: 7z x sty.zip

      - name: Test stresty
        run:  ./sty --path=./ --format=report --ns=servers test

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
